### ISSUE TITLE
I can't run opendistro with my own certificates

### ISSUE THREAD

**Issue by chanyshev** [opendistro-for-elasticsearch/security#1105]
Hi all, I'm trying to set up an opendistro in docker with self-written certificates. 
When I run the containers I see in the logs:
- kibana logs:
`":"log","@timestamp":"2021-03-27T09:26:53Z","tags":["error","elasticsearch","data"],"pid":1,"message":"[ConnectionError]: connect ECONNREFUSED 127.0.0.1:9200"}`
- odfe logs
```
java.lang.IllegalStateException: failed to load plugin class [com.amazon.opendistroforelasticsearch.security.OpenDistroSecurityPlugin]
Likely root cause: java.lang.IllegalArgumentException: No enum constant io.netty.handler.ssl.ClientAuth.optional
```

My docker-compose.yml:
```
version: '3'
services:
  web:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    links:
      - fluentd
    volumes:
      - ./nginx/app.conf:/etc/nginx/app.conf    
    logging: 
       driver: "fluentd"
       options:
         fluentd-address: localhost:24224
         tag: nginx.access
    networks:
      - odfe-net

  fluentd:
    build: ./fluentd
    environment:
      - "SSL_CERT_DIR=/fluentd/certs"
      - "SSL_CERT_FILE=/fluentd/certs/root-ca.pem"  
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - ./setup-ssl/:/fluentd/certs  
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - odfe-net

  odfe-node1:
    image: amazon/opendistro-for-elasticsearch:1.13.1 
    container_name: odfe-node1 
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping  
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the Elasticsearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - ./odfe/odfe-data1:/usr/share/elasticsearch/data
      - ./odfe/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./odfe/internal_users.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml
      - ./odfe/roles_mapping.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/roles_mapping.yml
      - ./odfe/tenants.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/tenants.yml
      - ./odfe/roles.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/roles.yml
      - ./odfe/action_groups.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/action_groups.yml
      - ./setup-ssl/root-ca.pem:/usr/share/elasticsearch/config/root-ca.pem
      - ./setup-ssl/odfe-node1.pem:/usr/share/elasticsearch/config/odfe-node1.pem
      - ./setup-ssl/odfe-node1-key.pem:/usr/share/elasticsearch/config/odfe-node1-key.pem
      - ./setup-ssl/kibana.pem:/usr/share/elasticsearch/config/kibana.pem
      - ./setup-ssl/kibana-key.pem:/usr/share/elasticsearch/config/kibana-key.pem
#      - ./setup-ssl/fluentd.pem:/usr/share/elasticsearch/config/fluentd.pem
#      - ./setup-ssl/fluentd.key:/usr/share/elasticsearch/config/fluentd.key
      - ./setup-ssl/admin.pem:/usr/share/elasticsearch/config/admin.pem
      - ./setup-ssl/admin-key.pem:/usr/share/elasticsearch/config/admin-key.pem
    ports:
      - "9200:9200"
      - "9600:9600" # required for Performance Analyzer
    networks:
      - odfe-net

  kibana:
    image: amazon/opendistro-for-elasticsearch-kibana:1.13.1
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=https://odfe-node1:9200
      - ELASTICSEARCH_USERNAME=kibanaserver
      - ELASTICSEARCH_PASSWORD=kibanaserver
#      - ELASTICSEARCH_HOSTS=https://odfe-node1:9200
#      - SERVER_SSL_ENABLED="true"
#      - SERVER_SSL_KEY=/usr/share/kibana/config/kibana-key.pem
#      - SERVER_SSL_CERTIFICATE=/usr/share/kibana/config/kibana.pem
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./setup-ssl/root-ca.pem:/usr/share/kibana/config/root-ca.pem
      - ./setup-ssl/kibana.pem:/usr/share/kibana/config/kibana.pem
      - ./setup-ssl/kibana-key.pem:/usr/share/kibana/config/kibana-key.pem
volumes:
  odfe-data1:
networks:
  odfe-net:
```

```

Elastic config elasticsearch.yml

cluster.name: "docker-cluster"
network.host: 0.0.0.0

# # minimum_master_nodes need to be explicitly set when bound on a public IP
# # set to 1 to allow single node clusters
# # Details: https://github.com/elastic/elasticsearch/pull/17288
discovery.zen.minimum_master_nodes: 1



# # Breaking change in 7.0
# # https://www.elastic.co/guide/en/elasticsearch/reference/7.0/breaking-changes-7.0.html#breaking_70_discovery_changes
# cluster.initial_master_nodes:
#    - elasticsearch1
#    - docker-test-node-1
######## Start OpenDistro for Elasticsearch Security Demo Configuration ########
# WARNING: revise all the lines below before you go into production
opendistro_security.ssl.transport.pemcert_filepath: odfe-node1.pem
opendistro_security.ssl.transport.pemkey_filepath: odfe-node1-key.pem
opendistro_security.ssl.transport.pemtrustedcas_filepath: root-ca.pem
opendistro_security.ssl.transport.enforce_hostname_verification: false
opendistro_security.ssl.http.enabled: true
opendistro_security.ssl.http.pemcert_filepath: odfe-node1.pem
opendistro_security.ssl.http.pemkey_filepath: odfe-node1-key.pem
opendistro_security.ssl.http.pemtrustedcas_filepath: root-ca.pem
opendistro_security.ssl.http.clientauth_mode: optional
#opendistro_security.allow_unsafe_democertificates: true
opendistro_security.allow_default_init_securityindex: true
opendistro_security.authcz.admin_dn:
  - 'CN=admin,O=Company,L=Moscow,ST=Some-State,C=RU'
#  - 'CN=odfe-node1,OU=UNIT,O=ORG,L=Moscow,ST=ONTARIO,C=CA'
#  - CN=fluentd,O=Company,L=Moscow,ST=Some-State,C=RU
#  - CN=kibana,O=Company,L=Moscow,ST=Some-State,C=RU
#  - CN=odfe-node1,O=Company,L=Moscow,ST=Some-State,C=RU
#  - CN=admin,O=Company,L=Moscow,ST=Some-State,C=RU
opendistro_security.nodes_dn:
  - 'CN=odfe-node1,O=Company,L=Moscow,ST=Some-State,C=RU'
  - 'CN=kibana,O=Company,L=Moscow,ST=Some-State,C=RU'
opendistro_security.audit.type: internal_elasticsearch
opendistro_security.enable_snapshot_restore_privilege: true
opendistro_security.check_snapshot_restore_write_privileges: true
opendistro_security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]
#opendistro_security.system_indices.enabled: true
#opendistro_security.system_indices.indices: [".opendistro-alerting-config", ".opendistro-alerting-alert*", ".opendistro-anomaly-results*", ".opendistro-anomaly-detector*", ".opendistro-anomaly-checkpoints", ".opendistro-anomaly-detection-state", ".opendistro-reports-*", ".opendistro-notifications-*", ".opendistro-notebooks", ".opendistro-asynchronous-search-response*"]
cluster.routing.allocation.disk.threshold_enabled: false
#node.max_local_storage_nodes: 3
opendistro_security.audit.config.disabled_rest_categories: NONE
opendistro_security.audit.config.disabled_transport_categories: NONE
######## End OpenDistro for Elasticsearch Security Demo Configuration ########
```
