### ISSUE TITLE
Incorrect behaviour from permissions system under certain conditions

### ISSUE THREAD

**Issue by m4rkw** [opendistro-for-elasticsearch/security#1114]
This seems to be a bug in OpenDistro security v0.10.0.

Given:

 - two indexes in the cluster - test-2021.04.06 and test-index-2021.04.06
 - a role that allows read access to all indices except two specific indices (via regex) test-202* and test-index-202*
 - another role that grants read access to one of the excluded indices - test-202*
 - another role that grants read access to the other excluded index - test-index-202*

A user with these roles then querying test-* will get a permission denied error despite having read permissions for both of the indices in the cluster that match this prefix. Both indices can be queried separately. If the role with the regex is removed this is no longer the case. Audit logging was enabled and inspected to confirm that when access is denied there are no other indices matching the query pattern for which the user has no read access.

Example config:

internal_users.yml
````
elastic:
  hash: "$2a$10$qL2bCqWDxW0ZhHZV3Uvws.gtkXlkAgsq94uYWlOrv5mTYg2KJgOr." #elastic
  roles:
    - admin

test_user:
  hash: "$2a$10$tCrVl88Rnawm5RxKnwHeh.9eihIDQH32OGdA/c959/f6ny/ZgoKoi" #test
  roles:
    - test_user
````

roles.yml
````
all_access:
  readonly: true
  cluster:
    - UNLIMITED
  indices:
    '*':
      '*':
        - UNLIMITED
  tenants:
    admin_tenant: RW

readmost_role:
  cluster:
    - CLUSTER_MONITOR
    - INDICES_MONITOR
    - CLUSTER_COMPOSITE_OPS_RO
  indices:
    "/^((?!^(test-20|test-index-20))\\S)*$/":
      '*':
        - READ
        - SEARCH
        - MONITOR
        - VIEW_INDEX_METADATA

test_readonly_role:
  cluster:
    - CLUSTER_MONITOR
    - INDICES_MONITOR
    - CLUSTER_COMPOSITE_OPS_RO
  indices:
    "test-202*":
      '*':
        - READ
        - SEARCH
        - MONITOR
        - VIEW_INDEX_METADATA

testindex_readonly_role:
  cluster:
    - CLUSTER_MONITOR
    - INDICES_MONITOR
    - CLUSTER_COMPOSITE_OPS_RO
  indices:
    "test-index-202*":
      '*':
        - READ
        - SEARCH
        - MONITOR
        - VIEW_INDEX_METADATA
````

roles_mapping.yml
````
all_access:
  backendroles:
    - admin

test_readonly_role:
  backendroles:
    - test_user

testindex_readonly_role:
  backendroles:
    - test_user

readmost_role:
  users:
    - '*'
````

Steps to reproduce:

1. Apply the security config above

2. Create the test indices
````
$ curl -su elastic:elastic http://localhost:9200/test-2021.04.06/_doc/1 -H 'content-type:application/json' -d '{"one":"one"}'
$ curl -su elastic:elastic http://localhost:9200/test-2021.04.06/_doc/1 -H 'content-type:application/json' -d '{"one":"one"}'
````

3. Confirm test_user can read the first index:

````
$ curl -su test_user:test http://localhost:9200/test-2*/_search
{"took":7,"timed_out":false,"_shards":{"total":5,"successful":5,"skipped":0,"failed":0},"hits":{"total":1,"max_score":1.0,"hits":[{"_index":"test-2021.04.06","_type":"_doc","_id":"1","_score":1.0,"_source":{"one":"one"}}]}}
````

4. Confirm test_user can read the second index:
````
$ curl -su test_user:test http://localhost:9200/test-index-2*/_search
{"took":7,"timed_out":false,"_shards":{"total":5,"successful":5,"skipped":0,"failed":0},"hits":{"total":1,"max_score":1.0,"hits":[{"_index":"test-index-2021.04.06","_type":"_doc","_id":"1","_score":1.0,"_source":{"one":"one"}}]}}
````

A wildcard search should return data from both indices:

````
$ curl -su test_user:test http://localhost:9200/test-*/_search
````

EXPECTED RESULT:

````
{"took":32,"timed_out":false,"_shards":{"total":10,"successful":10,"skipped":0,"failed":0},"hits":{"total":2,"max_score":1.0,"hits":[{"_index":"test-2021.04.06","_type":"_doc","_id":"1","_score":1.0,"_source":{"one":"one"}},{"_index":"test-index-2021.04.06","_type":"_doc","_id":"1","_score":1.0,"_source":{"one":"one"}}]}}
````

ACTUAL RESULT:

````
{"error":{"root_cause":[{"type":"security_exception","reason":"no permissions for [indices:data/read/search] and User [name=test_user, roles=[test_user] requestedTenant=null]"}],"type":"security_exception","reason":"no permissions for [indices:data/read/search] and User [name=test_user, roles=[test_user] requestedTenant=null]"},"status":403}
````

If I remove the readmost_role from the user's permissions the query for test-* then succeeds. I have tried enabling audit logging and when the request is denied there are no other indices indicated in the list of indices that match the query. Therefore the only conclusion I can draw is that this is a bug.
