### ISSUE TITLE
Is there something special about the all_access role?

### ISSUE THREAD

**Issue by seafoodbuffet** [opendistro-for-elasticsearch/security#20]
I tried to create a new role that matches the same permissions as the all_access role:
```
all_access:
  readonly: true
  cluster:
    - UNLIMITED
  indices:
    '*':
      '*':
        - UNLIMITED
  tenants:
    admin_tenant: RW

all_admin:
  readonly: true
  cluster:
    - UNLIMITED
  indices:
    '*':
      '*':
        - UNLIMITED
  tenants:
    admin_tenant: RW
```

I've got LDAP authentication setup. If I map my ldap group to the all_admin role, the user sees less than if I map the same group to the all_access role. Specifically, when clicking on Security in Kibana, mapping to the all_admin role (the one I created) I only see Authentication and Authorization. And clicking on it kicks me out of Kibana. Is there something "special" about that all_access role that I can't duplicate using a custom role?
