### ISSUE TITLE
ClassNotFoundException: extended-proxy

### ISSUE THREAD

**Issue by ajwild** [opendistro-for-elasticsearch/security#212]
I have setup Elasticsearch and Kibana using proxy authentication and everything is working as expected. I then tried to switch to using extended-proxy so that I could send additional header values to use in document level security conditions. I found that changing `type: proxy` to `type: extended-proxy` in config.yml caused the following error when running securityadmin.sh:
```
Unable to initialize auth domain proxy_auth_domain=AuthcDomain [http_enabled=true, transport_enabled=true, order=0, http_authenticator=HttpAuthenticator [challenge=true, type=extended-proxy, config={}], authentication_backend=AuthcBackend [type=noop, config={}], description=null] due to ElasticsearchException[java.lang.ClassNotFoundException: extended-proxy]; nested: ClassNotFoundException[extended-proxy];
```

To keep it simple you can use the following two (minimal) configuration files to recreate the error:

docker-compose.yml:
```
version: "2"
services:
  odfe-test:
    environment:
      - discovery.type=single-node
    image: amazon/opendistro-for-elasticsearch:1.3.0
    volumes:
      - odfe-data:/usr/share/elasticsearch/data
      - ./config.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/config.yml
volumes:
  odfe-data:
```

config.yml:
```
_meta:
  type: config
  config_version: 2

config:
  dynamic:
    authc:
      proxy_auth_domain:
        http_authenticator:
          type: extended-proxy
        authentication_backend:
          type: noop
```

It looks like this authentication method was introduced in version 1.2.1 (see #174), so have also tried with the amazon/opendistro-for-elasticsearch:1.2.1 image, but this has the same issue.

I then found the previous pull request for version 0.10.0 (see #85) and with this I do not get the error message. I haven't had time to switch to this version and test end-to-end yet as my config files are not compatible.

I assume it's something to do with the rebase/update for v1 and the comment from https://github.com/opendistro-for-elasticsearch/security/pull/85#issuecomment-552696341. @allenyin96 @jcantrill any insight into what the cause might be?
