### ISSUE TITLE
Login to Elasticsearch through jwt

### ISSUE THREAD

**Issue by davide-malagoli** [opendistro-for-elasticsearch/security#230]
I tried following this example, it does not work for me.

https://aws.amazon.com/it/blogs/opensource/json-web-tokens-jwt-authenticate-open-distro-for-elasticsearch-kibana/

I’m using this

**docker-compose.xml**

```
version: '3'
services:
  odfe-node1:
    image: amazon/opendistro-for-elasticsearch:1.3.0
    container_name: odfe-node1
    environment:
      - cluster.name=odfe-cluster
      - node.name=odfe-node1
      - discovery.type=single-node
	#- discovery.seed_hosts=odfe-node1,odfe-node2
	#- cluster.initial_master_nodes=odfe-node1,odfe-node2
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      memlock:
	soft: -1
	hard: -1
      nofile:
	soft: 65536 # maximum number of open files for the Elasticsearch user, set to at least 65536 on modern systems
	hard: 65536
    volumes:
      - /home/davidemalagoli/kibana/custom-docker/community/config.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/config.yml
      - odfe-data1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - odfe-net
	
  kibana:
    image: amazon/opendistro-for-elasticsearch-kibana:1.3.0
    container_name: odfe-kibana
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      ELASTICSEARCH_URL: https://odfe-node1:9200
      ELASTICSEARCH_HOSTS: https://odfe-node1:9200
    networks:
      - odfe-net

volumes:
  odfe-data1:
  odfe-data2:

networks:
  odfe-net:
```
and following

**config.xml**

```
_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    http:
      anonymous_auth_enabled: false
      xff:
	enabled: false
    authc:
      basic_internal_auth_domain:
	description: "Authenticate via HTTP Basic against internal users database"
	http_enabled: false
	transport_enabled: false
	order: 4
	http_authenticator:
	  type: basic
	  challenge: true
	authentication_backend:
	  type: intern
      jwt_auth_domain:
	http_enabled: true
	transport_enabled: false
	order: 0
	http_authenticator:
	  type: jwt
	  challenge: false
	  config:
	    signing_key: "c2VjcmV0"
	    jwt_header: null
	    jwt_url_parameter: "jwt"
	    roles_key: "roles"
	    subject_key: "sub"
	authentication_backend:
	  type: noop
    authz:
      roles_from_myldap:
	description: "Authorize via LDAP or Active Directory"
	http_enabled: false
	transport_enabled: false
	authorization_backend:
	  # LDAP authorization backend (gather roles from a LDAP or Active Directory, you have to configure the above LDAP authentication backend settings too)
	  type: ldap
	  config:
	    # enable ldaps
	    enable_ssl: false
	    # enable start tls, enable_ssl should be false
	    enable_start_tls: false
	    # send client certificate
	    enable_ssl_client_auth: false
	    # verify ldap hostname
	    verify_hostnames: true
	    hosts:
	    - localhost:8389
	    bind_dn: null
	    password: null
	    rolebase: 'ou=groups,dc=example,dc=com'
	    # Filter to search for roles (currently in the whole subtree beneath rolebase)
	    # {0} is substituted with the DN of the user
	    # {1} is substituted with the username
	    # {2} is substituted with an attribute value from user's directory entry, of the authenticated user. Use userroleattribute to specify the name of the attribute
	    rolesearch: '(member={0})'
	    # Specify the name of the attribute which value should be substituted with {2} above
	    userroleattribute: null
	    # Roles as an attribute of the user entry
	    userrolename: disabled
	    #userrolename: memberOf
	    # The attribute in a role entry containing the name of that role, Default is "name".
	    # Can also be "dn" to use the full DN as rolename.
	    rolename: cn
	    # Resolve nested roles transitive (roles which are members of other roles and so on ...)
	    resolve_nested_roles: true
	    userbase: 'ou=people,dc=example,dc=com'
	    # Filter to search for users (currently in the whole subtree beneath userbase)
	    # {0} is substituted with the username
	    usersearch: '(uid={0})'
	    # Skip users matching a user name, a wildcard or a regex pattern
	    #skip_users:
	    #  - 'cn=Michael Jackson,ou*people,o=TEST'
	    #  - '/\S*/'
      roles_from_another_ldap:
	description: "Authorize via another Active Directory"
	http_enabled: false
	transport_enabled: false
	authorization_backend:
	  type: ldap
	  #config goes here ...
  #    auth_failure_listeners:
  #      ip_rate_limiting:
  #        type: ip
  #        allowed_tries: 10
  #        time_window_seconds: 3600
  #        block_expiry_seconds: 600
  #        max_blocked_clients: 100000
  #        max_tracked_clients: 100000
  #      internal_authentication_backend_limiting:
  #        type: username
  #        authentication_backend: intern
  #        allowed_tries: 10
  #        time_window_seconds: 3600
  #        block_expiry_seconds: 600
  #        max_blocked_clients: 100000
  #        max_tracked_clients: 100000
```
In no way I am able to obtain a positive response from

`curl -v -XGET https://localhost:9200/_cat/nodes?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsIm5hbWUiOiJKb2huIERvZSIsImlhdCI6MTUxNjIzOTAyMiwicm9sZXMiOiJhZG1pbiJ9.SPgn7KcBxJRHzUqO-65mElicejY8zxo-Znn2cNtFAjs --insecure`

I validated the JWT contents using

https://jwt.io/

```
{
  "sub": "admin",
 "name": "John Doe",
 "iat": 1516239022,
"roles": "admin"
}
```
Can anyone help me, please?

Thank you
