### ISSUE TITLE
Client log spam: "WARNING: Compact JWS does not have 3 parts"

### ISSUE THREAD

**Issue by DandyDeveloper** [opendistro-for-elasticsearch/security#376]
This is similar to the issue reported here: https://github.com/opendistro-for-elasticsearch/security/issues/176

However, I am not impacted too hard by this problem I would just like to know where / how we can prevent this warning from happening.

All the client nodes are receiving events from a fluentd instance and are reporting this when using a hard-coded user in a OIDC setup environment: 

```
WARNING: Compact JWS does not have 3 parts
Apr 12, 2020 9:00:17 PM org.apache.cxf.rs.security.jose.jws.JwsCompactConsumer <init>
WARNING: Compact JWS does not have 3 parts
Apr 12, 2020 9:00:17 PM org.apache.cxf.rs.security.jose.jws.JwsCompactConsumer <init>
WARNING: Compact JWS does not have 3 parts
```

Since upgrading to 1.4.0 we've got an additional message which shows the class handling the token.. However, this is just adding to the spam. 

Does anyone know why this occurs?

**Comment by DandyDeveloper** [comment]
Looks like it's what you'd expect: 

https://github.com/apache/cxf/blob/master/rt/rs/security/jose-parent/jose/src/main/java/org/apache/cxf/rs/security/jose/jws/JwsCompactConsumer.java#L52

The problem is clear but not the root cause... I'm guessing the tokens generated for users when OIDC is enabled is different from normal logins?

**Comment by DandyDeveloper** [comment]
@hardik-k-shah @shivdoshi 

Can I get some suggestions on this?

**Comment by wyllys66** [comment]
I see the same issue using Keycloak as the OpenId provider. Using opendistro version 1.7.0

**Comment by dinusX** [comment]
Hi,

According to the JWT documentation the token should have 3 parts: header, body and signature.
I'm suspecting that maybe your JWT tokens don't have signature.

Could you take one of the tokens and try to crack it using the following website: https://jwt.io/
This should give you more data about the missing part.

Also, check in your application if there is any setting to enable signing of the jwt tokens.

**Comment by DandyDeveloper** [comment]
@dinusX Which JWT? It looks like there are session tokens generated through the OIDC proivder login. 

Where is the JWT stored for a session auth? I looked at my login chain and I see no JWT generated at any point. Is this a server side request that we don't see?

**Comment by DandyDeveloper** [comment]
@dinusX Any news on this? I'm still a bit confused on which JWT you're referring to here?

**Comment by vrozov** [comment]
@DandyDeveloper Have you tried changing priority order of openid and basic authenticator to avoid the warning message?

**Comment by wyllys66** [comment]
Can someone recommend a way to just turn off the logging?  I've tried adding entries to log4j2.properties and also setting the transient log properties as follows:

```
PUT _cluster/settings
{
  "transient": {
    "logger.org.apache.cxf.rs.security.jose.jws.JwsCompactConsumer": "fatal"
  }
}
```

But nothing works, it constantly spews that message to stderr. It is especially spammy when you have logstash constantly sending updates and using standard authentication (not JWS).

Apparently org.apache.cxf logging is a little different, but I cannot figure out how to configure it to just use the log4j2 properties like the rest of elasticsearch.

**Comment by dinusX** [comment]
Hi @wyllys66 ,

- Do you have both basic auth and JWT enabled ?
- If yes, what is the order that you use ? (You can check configuration and order using API: /_opendistro/_security/api/securityconfig )
- For logstash do you use basic auth (user+password) ?

**Comment by wyllys66** [comment]
Yes, JWT first, then Basic.   

Logstash uses Basic only.

**Comment by wyllys66** [comment]
I got it to work by arranging the authenticators so that basic was tried once with "challenge" set to False, then it attempts OpenID (JWT), then it will try Basic again with "challenge" set to True.   It's kind of a hack, but at least Im not being flooded with those messages anymore.

Example:
```
_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    http:
      anonymous_auth_enabled: false
    authc:
      basic_internal_auth_domain:
        description: "Authenticate via HTTP Basic against internal users database (no challenge)"
        http_enabled: true
        transport_enabled: true
        order: 0
        http_authenticator:
          type: basic
          challenge: false
        authentication_backend:
          type: intern
      openid_auth_domain:
        description: "Authenticate via Open ID Auth Token"
        http_enabled: true
        transport_enabled: true
        order: 1
        http_authenticator:
          type: openid
          challenge: false
          config:
            openid_connect_url: http://KEYCLOAK_SERVER/auth/realms/REALM/.well-known/openid-configuration
            roles_key: roles
            subject_key: sub
        authentication_backend:
          type: noop
      basic_internal_auth_domain_2:
        description: "Authenticate via HTTP Basic against internal users database (challenge if no auth)"
        http_enabled: true
        transport_enabled: true
        order: 2
        http_authenticator:
          type: basic
          challenge: true
        authentication_backend:
          type: intern
```
