### ISSUE TITLE
Internal User Database + LDAP: ElasticsearchSecurityException[No user kibanaserver found] 

### ISSUE THREAD

**Issue by weand** [opendistro-for-elasticsearch/security#431]
We have LDAP and Internal User Storage configured in parallel for http authentication. Use Case is,  that users accessing Kibana can use their LDAP Credentials and the communication between Kibana Server and Elasticsearch is secured with internal user (and also other Services accessing the Elasticsearch REST API use service users maintained in internal user database).

The authentication works successfully, but each time the Kibana Server tries to authenticate for accessing Elasticsearch this *ERROR* log line pops up in log: `org.elasticsearch.ElasticsearchSecurityException: ElasticsearchSecurityException[No user kibanaserver found]` with `com.amazon.dlic.auth.ldap.backend.LDAPAuthorizationBackend` in stacktrace. 

We already use Internal Auth Backend with `order: 1` and LDAP Auth Backend with `order: 2`, see security configuration excerpt:
```
...
    authc:
      basic_internal_auth_domain:
        http_enabled: true
        transport_enabled: false
        order: 1
        http_authenticator:
          type: basic
          challenge: true
        authentication_backend:
          type: intern
      ldap:
        http_enabled: true
        transport_enabled: false
        order: 2
        http_authenticator:
          type: basic
          challenge: true
        authentication_backend:
          # LDAP authentication backend (authenticate users against a LDAP or Active Directory)
          type: ldap
          ...
```

Expected behavior: LDAP ist not queried at all when authentication against Internal User Storage already succeeded. Or that the message is suppressed. Or that the message is DEBUG level.

Full Stacktrace:

```node1     | [2019-11-25T15:15:04,511][ERROR][c.a.o.s.a.BackendRegistry] [node1] Cannot retrieve roles for User [name=kibanaserver, roles=[admin], requestedTenant=null] from ldap due to ElasticsearchSecurityException[ElasticsearchSecurityException[No user kibanaserver found]]; nested: ElasticsearchSecurityException[No user kibanaserver found];
node1     | org.elasticsearch.ElasticsearchSecurityException: ElasticsearchSecurityException[No user kibanaserver found]
node1     |     at com.amazon.dlic.auth.ldap.backend.LDAPAuthorizationBackend.fillRoles(LDAPAuthorizationBackend.java:854) ~[opendistro_security_advanced_modules-1.2.1.0.jar:1.2.1.0]
node1     |     at com.amazon.opendistroforelasticsearch.security.auth.BackendRegistry.authz(BackendRegistry.java:622) [opendistro_security-1.2.1.0.jar:1.2.1.0]
node1     |     at com.amazon.opendistroforelasticsearch.security.auth.BackendRegistry.access$000(BackendRegistry.java:84) [opendistro_security-1.2.1.0.jar:1.2.1.0]
node1     |     at com.amazon.opendistroforelasticsearch.security.auth.BackendRegistry$9.call(BackendRegistry.java:663) [opendistro_security-1.2.1.0.jar:1.2.1.0]
node1     |     at com.amazon.opendistroforelasticsearch.security.auth.BackendRegistry$9.call(BackendRegistry.java:655) [opendistro_security-1.2.1.0.jar:1.2.1.0]
node1     |     at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4875) [guava-25.1-jre.jar:?]
node1     |     at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527) [guava-25.1-jre.jar:?]
node1     |     at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2276) [guava-25.1-jre.jar:?]
node1     |     at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154) [guava-25.1-jre.jar:?]
node1     |     at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044) [guava-25.1-jre.jar:?]
node1     |     at com.google.common.cache.LocalCache.get(LocalCache.java:3951) [guava-25.1-jre.jar:?]
node1     |     at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4870) [guava-25.1-jre.jar:?]
node1     |     at com.amazon.opendistroforelasticsearch.security.auth.BackendRegistry.authcz(BackendRegistry.java:655) [opendistro_security-1.2.1.0.jar:1.2.1.0]
node1     |     at com.amazon.opendistroforelasticsearch.security.auth.BackendRegistry.authenticate(BackendRegistry.java:461) [opendistro_security-1.2.1.0.jar:1.2.1.0]
node1     |     at com.amazon.opendistroforelasticsearch.security.filter.OpenDistroSecurityRestFilter.checkAndAuthenticateRequest(OpenDistroSecurityRestFilter.java:146) [opendistro_security-1.2.1.0.jar:1.2.1.0]
...
```

**Comment by palashhedau** [comment]
Can you turn on the debug logs? It can give more insights on this

It looks the username is not a validDn. 
https://github.com/opendistro-for-elasticsearch/security/blob/ed6f901838e80e14116057bbffde02a3cf89e27e/src/main/java/com/amazon/dlic/auth/ldap/backend/LDAPAuthorizationBackend.java#L734

In that case, according to the settings specified in the config, it will check for the first occurrence of the user or will check all the base. 
https://github.com/opendistro-for-elasticsearch/security/blob/ed6f901838e80e14116057bbffde02a3cf89e27e/src/main/java/com/amazon/dlic/auth/ldap/backend/LDAPAuthenticationBackend.java#L208

**Comment by yoke88** [comment]
we current include a skip_users to work around this

```yaml
   authz:
      roles_from_myldap:
        description: "Authorize via LDAP or Active Directory"
        http_enabled: true
        transport_enabled: false
        authorization_backend:
          type: "ldap"
          config:
            enable_ssl: false
            enable_start_tls: false
            enable_ssl_client_auth: false
            verify_hostnames: true
            hosts:
            - "dc-xxx.domain.com:389"
            bind_dn: "CN=es_ldap,OU=AppReserved,DC=domain,DC=com"
            password: "password"
            rolebase: "DC=domain,DC=com"
            rolesearch: "(member={0})"
            userroleattribute: null
            userrolename: "disabled"
            rolename: "cn"
            resolve_nested_roles: true
            userbase: "DC=domain,DC=com"
            usersearch: "(uid={0})"
            skip_users:
            - "kibanaserver"
            - "admin"

```
