### ISSUE TITLE
Support for set_security_user ingest processor

### ISSUE THREAD

**Issue by dpotapov** [opendistro-for-elasticsearch/security#439]
I was going to use document-level security feature, but stuck with the fact that I cannot restrict users to access only their documents.
Such use case is described here: [Pre-processing documents to add security details](https://www.elastic.co/guide/en/elastic-stack-overview/current/field-and-document-access-control.html#set-security-user-processor). And it turns out that set_security_user feature seems not implemented in OpenDistro:

```yaml
PUT _ingest/pipeline/my-pipeline-id
description: set user
processors:
  - set_security_user:
      field: user
---
error:
  root_cause:
  - type: "parse_exception"
    reason: "No processor type exists with name [set_security_user]"
    header:
      processor_type: "set_security_user"
  type: "parse_exception"
  reason: "No processor type exists with name [set_security_user]"
  header:
    processor_type: "set_security_user"
status: 400
```

Would it possible to implement this processor? Is there any workaround?
