### ISSUE TITLE
LDAP Authentication Finally Failed for User using StartTLS

### ISSUE THREAD

**Issue by tfmm** [opendistro-for-elasticsearch/security#489]
Using LDAP (FreeIPA to be specific) for authentication and authorization. When I login with a built-in user (admin) I can login to kibana or ES without issues. When using a user from LDAP, Kibana and ES immediately return Invalid username or password errors. 

Checking logs from LDAP side, I see a successful bind and search for my username. 

Here's my config.yml:

```
---
_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    # Set filtered_alias_mode to 'disallow' to forbid more than 2 filtered aliases per index
    # Set filtered_alias_mode to 'warn' to allow more than 2 filtered aliases per index but warns about it (default)
    # Set filtered_alias_mode to 'nowarn' to allow more than 2 filtered aliases per index silently
    #filtered_alias_mode: warn
    #do_not_fail_on_forbidden: false
    #kibana:
    # Kibana multitenancy
    #multitenancy_enabled: true
    #server_username: kibanaserver
    #index: '.kibana'
    http:
      anonymous_auth_enabled: false
      xff:
        enabled: false
        internalProxies: '192\.168\.0\.10|192\.168\.0\.11' # regex pattern
        #internalProxies: '.*' # trust all internal proxies, regex pattern
        #remoteIpHeader:  'x-forwarded-for'
        ###### see https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html for regex help
        ###### more information about XFF https://en.wikipedia.org/wiki/X-Forwarded-For
        ###### and here https://tools.ietf.org/html/rfc7239
        ###### and https://tomcat.apache.org/tomcat-8.0-doc/config/valve.html#Remote_IP_Valve
    authc:
      basic_internal_auth_domain:
        description: "Authenticate via HTTP Basic against internal users database"
        http_enabled: true
        transport_enabled: true
        order: 4
        http_authenticator:
          type: basic
          challenge: true
        authentication_backend:
          type: intern
      ldap:
        description: "Authenticate via LDAP or Active Directory"
        http_enabled: true
        transport_enabled: true
        order: 1
        http_authenticator:
          type: basic
          challenge: true
        authentication_backend:
          # LDAP authentication backend (authenticate users against a LDAP or Active Directory)
          type: ldap
          config:
            pemtrustedcas_filepath: /usr/share/elasticsearch/config/trusted_cas.pem
            # enable ldaps
            enable_ssl: false
            # enable start tls, enable_ssl should be false
            enable_start_tls: false
            # send client certificate
            enable_ssl_client_auth: false
            # verify ldap hostname
            verify_hostnames: false
            hosts:
              - master.ipa.example.com:389
            bind_dn: uid=ldap-readonly,cn=users,cn=accounts,dc=ipa,dc=example,dc=com
            password: pretendthisisapassword
            userbase: "dc=ipa,dc=example,dc=com"
            # Filter to search for users (currently in the whole subtree beneath userbase)
            # {0} is substituted with the username
            usersearch: '(uid={0})'
            # Use this attribute from the user as username (if not set then DN is used)
            username_attribute: 'uid'
    authz:
      roles_from_myldap:
        description: "Authorize via LDAP or Active Directory"
        http_enabled: true
        transport_enabled: true
        authorization_backend:
          # LDAP authorization backend (gather roles from a LDAP or Active Directory, you have to configure the above LDAP authentication backend settings too)
          type: ldap
          config:
            pemtrustedcas_filepath: /usr/share/elasticsearch/config/trusted_cas.pem
            # enable ldaps
            enable_ssl: false
            # enable start tls, enable_ssl should be false
            enable_start_tls: false
            # send client certificate
            enable_ssl_client_auth: false
            # verify ldap hostname
            verify_hostnames: false
            hosts:
              - master.ipa.example.com:389
            bind_dn: uid=ldap-readonly,cn=users,cn=accounts,dc=ipa,dc=example,dc=com
            password: pretendthisisapassword
            rolebase: 'dc=ipa,dc=example,dc=com'
            # Filter to search for roles (currently in the whole subtree beneath rolebase)
            # {0} is substituted with the DN of the user
            # {1} is substituted with the username
            # {2} is substituted with an attribute value from user's directory entry, of the authenticated user. Use userroleattribute to specify the name of the attribute
            rolesearch: '(memberUid={1})'
            # Specify the name of the attribute which value should be substituted with {2} above
            userroleattribute: 'uid'
            # Roles as an attribute of the user entry
            userrolename: 'memberOf'
            #userrolename: memberOf
            # The attribute in a role entry containing the name of that role, Default is "name".
            # Can also be "dn" to use the full DN as rolename.
            rolename: cn
            # Resolve nested roles transitive (roles which are members of other roles and so on ...)
            resolve_nested_roles: true
            userbase: 'dc=ipa,dc=example,dc=com'
            # Filter to search for users (currently in the whole subtree beneath userbase)
            # {0} is substituted with the username
            usersearch: '(uid={0})'
            # Skip users matching a user name, a wildcard or a regex pattern
            skip_users:
              - kibanaserver
```

Additionally, if I enable TLS, the connection fails to the LDAP server, and LDAP shows an unexpected end of file error. 

Both with and without TLS enabled, ES reports this when I try to auth:

```

[2020-06-03T14:55:45,848][WARN ][c.a.o.s.a.BackendRegistry] [odfe-node1] Authentication finally failed for ldapuser from 172.22.0.4:56178```

**Comment by tfmm** [comment]
I think I found the issue, it appears that the security plugin does not search recursively through the userbase and rolebase entries. 

I updated my config.yml to include the full DN to where users and groups are stored, and authentication is now working.  Authorization is still not pulling in the right backend roles, but I'm still working on that. 

Updated config.yml:

```
---
_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    http:
      anonymous_auth_enabled: false
      xff:
        enabled: false
        internalProxies: '192\.168\.0\.10|192\.168\.0\.11' # regex pattern
    authc:
      basic_internal_auth_domain:
        description: "Authenticate via HTTP Basic against internal users database"
        http_enabled: true
        transport_enabled: true
        order: 4
        http_authenticator:
          type: basic
          challenge: true
        authentication_backend:
          type: intern
      ldap:
        description: "Authenticate via LDAP or Active Directory"
        http_enabled: true
        transport_enabled: true
        order: 1
        http_authenticator:
          type: basic
          challenge: true
        authentication_backend:
          # LDAP authentication backend (authenticate users against a LDAP or Active Directory)
          type: ldap
          config:
            pemtrustedcas_filepath: /usr/share/elasticsearch/config/trusted_cas.pem
            # enable ldaps
            enable_ssl: false
            # enable start tls, enable_ssl should be false
            enable_start_tls: false
            # send client certificate
            enable_ssl_client_auth: false
            # verify ldap hostname
            verify_hostnames: false
            hosts:
              - master.ipa.example.com:389
            bind_dn: uid=ldap-readonly,cn=users,cn=accounts,dc=ipa,dc=example,dc=com
            password: password
            #userbase: "cn=users,cn=accounts,dc=ipa,dc=example,dc=com"
            # Filter to search for users (currently in the whole subtree beneath userbase)
            # {0} is substituted with the username
            #usersearch: '(uid={0})'
            users:
              primary-userbase:
                base: "cn=users,cn=accounts,dc=ipa,dc=example,dc=com"
                search: '(uid={0})'
              secondary-userbase:
                base: "cn=users,cn=compat,dc=ipa,dc=example,dc=com"
                search: '(uid={0})'
            # Use this attribute from the user as username (if not set then DN is used)
            username_attribute: 'uid'

    authz:
      roles_from_myldap:
        description: "Authorize via LDAP or Active Directory"
        http_enabled: true
        transport_enabled: true
        authorization_backend:
          # LDAP authorization backend (gather roles from a LDAP or Active Directory, you have to configure the above LDAP authentication backend settings too)
          type: ldap
          config:
            pemtrustedcas_filepath: /usr/share/elasticsearch/config/trusted_cas.pem
            # enable ldaps
            enable_ssl: false
            # enable start tls, enable_ssl should be false
            enable_start_tls: false
            # send client certificate
            enable_ssl_client_auth: false
            # verify ldap hostname
            verify_hostnames: false
            hosts:
              - master.ipa.example.com:389
            bind_dn: uid=ldap-readonly,cn=users,cn=accounts,dc=ipa,dc=example,dc=com
            password: password
            #rolebase: 'dc=ipa,dc=example,dc=com'
            roles:
              primary-rolebase:
                base: "cn=groups,cn=accounts,dc=ipa,dc=example,dc=com"
                search: '(memberUid={1})'
              secondary-rolebase:
                base: "cn=groups,cn=compat,dc=ipa,dc=example,dc=com"
                search: '(memberUid={1})'
            # Filter to search for roles (currently in the whole subtree beneath rolebase)
            # {0} is substituted with the DN of the user
            # {1} is substituted with the username
            # {2} is substituted with an attribute value from user's directory entry, of the authenticated user. Use userroleattribute to specify the name of the attribute
            #rolesearch: '(memberUid={1})'
            # Specify the name of the attribute which value should be substituted with {2} above
            userroleattribute: 'uid'
            # Roles as an attribute of the user entry
            userrolename: 'memberOf'
            # The attribute in a role entry containing the name of that role, Default is "name".
            # Can also be "dn" to use the full DN as rolename.
            rolename: cn
            # Resolve nested roles transitive (roles which are members of other roles and so on ...)
            resolve_nested_roles: true
            users:
              primary-userbase: 
                base: "cn=users,cn=accounts,dc=ipa,dc=example,dc=com"
                search: '(uid={0})'
              secondary-userbase: 
                base: "cn=users,cn=compat,dc=ipa,dc=example,dc=com"
                search: '(uid={0})'
            skip_users:
              - kibanaserver
```

**Comment by tfmm** [comment]
Got the role mapping working correctly now as well. TLS is still showing an unexpected EOF error on the LDAP side. Any advice there would be appreciated. 

Config.yml:
```
---
_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    http:
      anonymous_auth_enabled: false
      xff:
        enabled: false
        internalProxies: '192\.168\.0\.10|192\.168\.0\.11' # regex pattern
    authc:
      basic_internal_auth_domain:
        description: "Authenticate via HTTP Basic against internal users database"
        http_enabled: true
        transport_enabled: true
        order: 4
        http_authenticator:
          type: basic
          challenge: true
        authentication_backend:
          type: intern
      ldap:
        description: "Authenticate via LDAP or Active Directory"
        http_enabled: true
        transport_enabled: true
        order: 1
        http_authenticator:
          type: basic
          challenge: true
        authentication_backend:
          type: ldap
          config:
            pemtrustedcas_filepath: /usr/share/elasticsearch/config/trusted_cas.pem
            enable_ssl: false
            enable_start_tls: true
            enable_ssl_client_auth: false
            verify_hostnames: false
            hosts:
              - master.ipa.example.com:389
            bind_dn: uid=ldap-readonly,cn=users,cn=accounts,dc=ipa,dc=example,dc=com
            password: password
            #userbase: "cn=users,cn=accounts,dc=ipa,dc=example,dc=com"
            # Filter to search for users (currently in the whole subtree beneath userbase)
            # {0} is substituted with the username
            #usersearch: '(uid={0})'
            users:
              primary-userbase:
                base: "cn=users,cn=accounts,dc=ipa,dc=example,dc=com"
                search: '(uid={0})'
              secondary-userbase:
                base: "cn=users,cn=compat,dc=ipa,dc=example,dc=com"
                search: '(uid={0})'
            username_attribute: 'uid'

    authz:
      roles_from_myldap:
        description: "Authorize via LDAP or Active Directory"
        http_enabled: true
        transport_enabled: true
        authorization_backend:
          type: ldap
          config:
            pemtrustedcas_filepath: /usr/share/elasticsearch/config/trusted_cas.pem
            enable_ssl: false
            enable_start_tls: true
            enable_ssl_client_auth: false
            verify_hostnames: false
            hosts:
              - master.ipa.example.com:389
            bind_dn: uid=ldap-readonly,cn=users,cn=accounts,dc=ipa,dc=example,dc=com
            password: password
            #rolebase: 'dc=ipa,dc=example,dc=com'
            roles:
              primary-rolebase:
                base: "cn=groups,cn=accounts,dc=ipa,dc=example,dc=com"
                search: '(memberUid={1})'
              secondary-rolebase:
                base: "cn=groups,cn=compat,dc=ipa,dc=example,dc=com"
                search: '(memberUid={1})'
            userroleattribute: null
            userrolename: none
            rolename: cn
            resolve_nested_roles: true
            users:
              primary-userbase: 
                base: "cn=users,cn=accounts,dc=ipa,dc=example,dc=com"
                search: '(uid={0})'
              secondary-userbase: 
                base: "cn=users,cn=compat,dc=ipa,dc=example,dc=com"
                search: '(uid={0})'
            skip_users:
              - kibanaserver
```
