### ISSUE TITLE
Add support of JWKS for JWT key retrieval

### ISSUE THREAD

**Issue by PPACI** [opendistro-for-elasticsearch/security#6]
Hi opendistro.
Thanks for the great work !

Considering the following use case.
1. User want to log with JWT
2. JWT are issued by a Keycloak (or other OpenID Connect) server
3. Keycloak is configured with multiple, rotating, public keys

In this scenario, I cannot know which key is currently used, thus I cannot add it to the `config.yml` file.
It's also a problem if my auth server generate key at boot and doesn't let me retrieve directly.

The solution here would be to implement the JWKS standards. In the case of Keycloak, it enable us to retrieve keys using an [url](https://www.keycloak.org/docs/latest/securing_apps/index.html#other-openid-connect-libraries).

As an example, Spring Security OAuth use this URL to automatically retrieve public key.
For reference : https://docs.spring.io/spring-security/site/docs/5.1.4.RELEASE/reference/htmlsingle/#oauth2resourceserver.

```yaml
security:
  oauth2:
    resourceserver:
      jwt:
        jwk-set-uri: https://idp.example.com/.well-known/jwks.json
```

Could we implement this in the security plugin ?
Thank you
