### ISSUE TITLE
SAML does not work with Okta or Azure AD - Open Distro 1.9.0

### ISSUE THREAD

**Issue by SitoRBJ** [opendistro-for-elasticsearch/security#655]
Hello everyone!!

In previous versions of Open Distro I have managed to set SAML with Okta and Azure Ad, but when setting it for **Open Distro 1.9.0** (Docker images) I can’t make it work, getting the error `customerror?type=samlConfigError` and not being able to see anything relevant in the logs. The same configuration that I use works in version 1.8.0, but when uploading to 1.9.0 it fails.

This is an example of my configuration in Azure AD:

```yaml
saml_auth_domain:
            http_enabled: true
            transport_enabled: true
            order: 1
            http_authenticator:
              type: saml
              challenge: true
              config:
                idp:
                  metadata_url: https://login.microsoftonline.com/...
                  entity_id: https://sts.windows.net/.../
                sp:
                  entity_id: odfe-saml-2
                kibana_url: <Kibana URL>
                roles_key: Roles
                exchange_key: 'MIIC...'           
            authentication_backend:
              type: noop
```
Okta sample:

```yaml
    authc:
      saml_auth_domain:
        http_enabled: true
        transport_enabled: true
        order: 1
        http_authenticator:
          type: saml
          challenge: true
          config:
            idp:
              metadata_url: https://....okta.com/...
              entity_id: http://www.okta.com/...
            sp:
              entity_id: odfe-saml
            kibana_url: <Kibana URL>
            roles_key: Roles
            exchange_key: MIID...
        authentication_backend:
          type: noop
```
Please, I need this to work. I appreciate all kinds of help.

Best regards
