### ISSUE TITLE
SSL certificate hot reloading compares two identical certificates

### ISSUE THREAD

**Issue by Tarasovych** [opendistro-for-elasticsearch/security#689]
Hello!

This issue relates #238.

Prehistory. I'm running Elasticsearch in Docker (`amazon/opendistro-for-elasticsearch:1.8.0` image).
Part of my `elasticsearch.yml`:
```yml
opendistro_security.ssl.transport.pemcert_filepath: fullchain.pem
opendistro_security.ssl.transport.pemkey_filepath: privkey.pem
opendistro_security.ssl.transport.pemtrustedcas_filepath: fullchain.pem
opendistro_security.ssl.transport.enforce_hostname_verification: false
opendistro_security.ssl.http.enabled: true
opendistro_security.ssl.http.pemcert_filepath: fullchain.pem
opendistro_security.ssl.http.pemkey_filepath: privkey.pem
opendistro_security.ssl.http.pemtrustedcas_filepath: fullchain.pem
opendistro_security.allow_unsafe_democertificates: false
opendistro_security.ssl_cert_reload_enabled: true
```
SSL certificates are mounted into container, my `docker-compose.yml`:
```yml
    volumes:
      # ...
      - ./privkey.pem:/usr/share/elasticsearch/config/privkey.pem
      - ./fullchain.pem:/usr/share/elasticsearch/config/fullchain.pem
      # ...
```

My issue: I can't hot reload SSL certificates.

What have I tried exactly:
1. Copy new certificate to host
2. *New certificate is being mounted into the container instantly
3. `_opendistro/_security/api/ssl/http/reloadcerts` fails with 
```
{"error":"ElasticsearchSecurityException[Error while initializing http SSL layer from PEM: java.lang.Exception: New certificates should not expire before the current ones.]; nested: Exception[New certificates should not expire before the current ones.];"}
```

I don't know Java good enough, but it seems like ["old" certificate is being retrieved from file as well as "new" certificate](https://github.com/opendistro-for-elasticsearch/security/blob/f5b3fda11ea423f0a17da7da8be983d3cd6f30d4/src/main/java/com/amazon/opendistroforelasticsearch/security/ssl/DefaultOpenDistroSecurityKeyStore.java#L301). So, in my case, two identical certificates (which were read from the same file) were compared. Because new certificate replaced old one (see step 1 and 2 from above).

I used to refresh SSL certificates only with node (container) restart.

I think, that only "new" certificate should be taken from filesystem, and the "old" one should be taken from remote server:
```
openssl s_client -showcerts -connect my-node.example.com:9200 </dev/null | openssl x509 -text | grep Validity -A 2
```

Or am I missing something? Thank you in advance!
