### ISSUE TITLE
Roles.yml has changed but no example on repo

### ISSUE THREAD

**Issue by DanCarrerasLexacom** [opendistro-for-elasticsearch/security#78]
As per summary, should I go to push the configuration files to securityadmin.sh to configure a new environment, I get the following error from opendistro_security:

`ERR: Seems /usr/share/elasticsearch/plugins/opendistro_security/securityconfig/roles.yml is not in Open Distro Security 7 format: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field \"cluster\" (class com.amazon.opendistroforelasticsearch.security.securityconf.impl.v7.RoleV7)`

My Roles.yml file is still in v6 format, but there is no documentation nor examples on this repo about how the new v7 format should be.

**Comment by DanCarrerasLexacom** [comment]
Have run the migration feature within securityadmin.sh, and whilst this has mostly resolved my issue, I can't help but feel there should be a lot more documentation on this new formatting of the config files.

**Comment by AkiJ5** [comment]
Hello!
I don't know how useful my comment will, but I saw config examples in new format there:
`https://github.com/opendistro-for-elasticsearch/security/tree/master/securityconfig `

**Comment by DanCarrerasLexacom** [comment]
> `https://github.com/opendistro-for-elasticsearch/security/tree/master/securityconfig `

YEah, I'm afraid that's where I was originally, and as you can see:

_meta:
  type: "roles"
  config_version: 2

some of the files show no examples or documentation on how they should be implemented.

**Comment by aetter** [comment]
Hi all, `roles.yml` is basically a blank slate (with some metadata) now that the predefined roles are added within the plugin itself. Example:

```yml
_meta:
  type: "roles"
  config_version: 2

your-custom-role:
  cluster_permissions:
    - CLUSTER_COMPOSITE_OPS
  index_permissions:
    - index_patterns:
      - '*'
      allowed_actions:
        - READ
  tenant_permissions:
    - tenant_patterns:
      - another_tenant
      allowed_actions:
        - KIBANA_ALL_WRITE
```

I'll leave this issue open until I get something into the documentation. Thanks!
