### ISSUE TITLE
Clarification regarding whitelist.yml configuration

### ISSUE THREAD

**Issue by OlleLarsson** [opendistro-for-elasticsearch/security#799]
Hi, I am a bit unsure of what is actually required to be in the [`whitelist.yml`](https://github.com/opendistro-for-elasticsearch/security/blob/master/securityconfig/whitelist.yml) configuration file.

Currently the default is 
```
_meta:
  type: "whitelist"
  config_version: 2
config:
  enabled: false
  requests:
    /_cluster/settings:
      - GET
    /_cat/nodes:
      - GET
```
This puzzles me as the documentation says
> Example 4:
> If you want to disable the whitelisting feature, set enabled to false.
>  enabled: false
>  requests:
>    /_cluster/settings:
>      - GET
>
>At this point, all APIs become whitelisted because the feature to whitelist is off, so requests is irrelevant.

Do I still have to set `config.requests` even though `config.enable: false` ? If that's the case, if would say that it is kind of a strage behaviour.

Maybe @rahulkarajgikar can provide some clarification regarding the config :slightly_smiling_face:  ?
