### ISSUE TITLE
unable to push the configuration files with securityadmin.sh

### ISSUE THREAD

**Issue by dbagarozza** [opendistro-for-elasticsearch/security#87]
I want to push the configuration files with securityadmin.sh, but i get the following error from opendistro_security:

Elasticsearch Version: 7.0.1
Open Distro Security Version: 1.0.0.0
Contacting elasticsearch 'elasticsearch' and wait for YELLOW clusterstate ...
Clustername: elasticsearch
Clusterstate: YELLOW
Number of nodes: 3
Number of data nodes: 1
.opendistro_security index already exists, so we do not need to create one.
Populate config from /usr/share/elasticsearch/plugins/opendistro_security/securityconfig
Will update '_doc/config' with ../securityconfig/config.yml 
   SUCC: Configuration for 'config' created or updated
Will update '_doc/roles' with ../securityconfig/roles.yml 
   SUCC: Configuration for 'roles' created or updated
Will update '_doc/rolesmapping' with ../securityconfig/roles_mapping.yml 
   SUCC: Configuration for 'rolesmapping' created or updated
Will update '_doc/internalusers' with ../securityconfig/internal_users.yml 
   SUCC: Configuration for 'internalusers' created or updated
Will update '_doc/actiongroups' with ../securityconfig/action_groups.yml 
   SUCC: Configuration for 'actiongroups' created or updated
Will update '_doc/tenants' with ../securityconfig/tenants.yml 
   SUCC: Configuration for 'tenants' created or updated
FAIL: 3 nodes reported failures. First failure is FailedNodeException[Failed node [jVWyt2ugRBy3z43iHmYfAw]]; nested: RemoteTransportException[[elasticsearch-client-6c5b7dcbc8-g7q95][][cluster:admin/opendistro_security/config/update[n]]]; nested: NotSerializableExceptionWrapper[static_resource_exception: Cannot override static roles];
FAIL: Expected 3 nodes to return response, but got 0
Done with failures

It works with the default configurations files.

**Comment by sgavrylenko** [comment]
have the same problem. My steps:
- run configs backup with `./securityadmin.sh -backup ...` on v0.9.0
- run with version v1.0.0
- run offline migration with `./securityadmin.sh -mo ....`
- run `./securityadmin.sh" -cd "../securityconfig" -icl -key "../../../config/kirk-key.pem" -cert "../../../config/kirk.pem" -cacert "../../../config/root-ca.pem" -nhnv`

**Comment by aetter** [comment]
Hi @dbagarozza, try removing any standard roles from your `roles.yml` (leave only the custom ones you created):

```yml
_meta:
  type: "roles"
  config_version: 2

my-custom-role:
  cluster_permissions:
    - CLUSTER_COMPOSITE_OPS
  index_permissions:
    - index_patterns:
      - '*'
      allowed_actions:
        - READ
  tenant_permissions:
    - tenant_patterns:
      - another_tenant
      allowed_actions:
        - KIBANA_ALL_WRITE
```

In 1.0.0, the built-in roles are now, well, built in, as opposed to being part of `roles.yml`. I believe that error is saying, "You're not allowed to override these roles."
